jobs:
  include:
    - stage: "s1"
      env: 
        - RUNSTEP=CSHARP 
      script:
        - ./build.sh 2>&1
      # artifacts: 
      #   debug: true
      #   paths: $HOME/data.json
      workspaces:
        create:
          name: ws1
          paths:
            - data.json
    - stage: "s1"
      workspaces:
        use:
        - ws1
      env: 
        - RUNSTEP=PY_JS_PHP 
      script: 
        - ./build.sh 2>&1
      # artifacts: 
      #   debug: true
      #   paths: $HOME/data.json

language: python
dist: jammy
python:
- 3.8.3
git:
  depth: 1
cache:
  directories:
  - ".cache"
before_install:
- set -e
- ". $HOME/.nvm/nvm.sh"
- nvm ls
- nvm ls-remote
- echo "runstepppppppppp"
- echo "$RUNSTEP"


addons:
  artifacts: 
    debug: true
    paths: data.json