jobs:
  include:
    - stage: "s1"
      env: 
        - RUNSTEP=CSHARP 
      script:
        - ./build.sh 2>&1
      workspaces:
        create:
          name: ws1
          paths:
            - data.json
    - stage: "s2"
      workspaces:
        create:
          name: ws1
          paths:
            - data.json
      env: 
        - RUNSTEP=PY_JS_PHP 
      script: 
        - ./build.sh 2>&1

language: python
dist: jammy
python:
- 3.8.3
git:
  depth: 1
cache:
  directories:
  - ".cache"
before_install:
- set -e
- ". $HOME/.nvm/nvm.sh"
- nvm ls
- nvm ls-remote
- echo "runstepppppppppp"
- echo $RUNSTEP
