env:
  jobs:
    - RUNSTEP=PY_JS_PHP
    - RUNSTEP=CSHARP


language: python
dist: jammy
python:
- 3.8.3
git:
  depth: 2
cache:
  directories:
  - ".cache"
before_install:
- set -e
- ". $HOME/.nvm/nvm.sh"
- nvm ls
- nvm ls-remote
- nvm install v18.17.0
- rm -rf node_modules
# common commands
- npm ci --include=dev
- git checkout package.json package-lock.json
- git config pull.rebase false
- if [ "$RUNSTEP" == "PY_JS_PHP" ]; then
    echo "$RUNSTEP 1"
  fi;
  if [ "$RUNSTEP" == "CSHARP" ]; then
    echo "$RUNSTEP 2"
  fi;

script: 
- ./build.sh 2>&1
- artifacts:
    paths:
      - data.json 