blank_issues_enabled: false
contact_links:
  - name: CCXT Documentation
    url: https://docs.ccxt.com/en/latest/manual.html
    about: Read CCXT documentation for answers to common questions
  - name: Troubleshooting
    url: https://docs.ccxt.com/en/latest/manual.html#troubleshooting
    about: Read our troubleshooting recommendations in our documentation
  - name: CCXT Discord
    url: https://gatsby.dev/discord
    about: Ask questions, get help and discuss new things you're building with the CCXT community
  - name: Programming questions
    url: https://stackoverflow.com/questions/ask?tags=ccxt
    about: Can't figure out why your code isn't working? Try asking on Stack Overflow
